# SPDX-License-Identifier: Apache-2.0
environment_name: latitude

# the folder in roles/hedera-docker/files/keys-signing/ to use for signing keys
environment_keys_signing_directory: latitude
environment_keys_tls_directory: latitude
