global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'sample-scrap'
    static_configs:
      - targets: ['host.docker.internal:38317']
    relabel_configs:
      - target_label: environment
        replacement: localhost
